version: "3.4"

services:
  
  api:
    container_name: hact-api-prod
    build:
      context: .
      target: production
    ports:
      - 4444:4444
    env_file:
      - .env.prod.example
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always







